export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_IN_PROGRESS = 'AUTH_IN_PROGRESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_UPDATE_TOKENS = 'AUTH_UPDATE_TOKENS';

export const THEME_SUCCESS = 'THEME_SUCCESS';
export const THEME_CHANGE_LANGUAGE = 'THEME_CHANGE_LANGUAGE';
export const THEME_CHANGE_SIDEBAR = 'THEME_CHANGE_SIDEBAR';