import { idSchema, idSchemaOptional, languageStringSchema, minorNumberSchema } from '@remnant/shared'
import { z } from 'zod'

const moneyTransactionActorSchema = z.object({
  id: z.string(),
  name: z.string().trim(),
}).nullable()

export const moneyTransactionSchema = z.object({
  _id: idSchema,
  seq: z.number(),
  type: z.enum(['income', 'cancelled', 'expense', 'transfer', 'refund', 'investment', 'purchase', 'procurement']),
  direction: z.enum(['in', 'out']),
  account: idSchema,
  minorAmount: minorNumberSchema,
  currencyId: idSchema,
  cashregisterId: idSchema,
  description: z.string().optional(),
  sourceModel: z.string(),
  sourceId: idSchema,
  role: z.enum(['from', 'to']).nullable().optional(),
  transferId: idSchemaOptional,
  confirmed: z.boolean(),
  confirmedBy: z.string().nullable().optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  createdBy: z.string().nullable().optional(),
  cancelled: z.boolean().optional(),
  cancelledBy: z.string().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  minorBalanceBefore: z.number().nullable().optional(),
  minorBalanceAfter: z.number().nullable().optional(),
  removed: z.boolean(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const moneyTransactionPopulatedSchema = z.object({
  id: idSchema,
  seq: z.number(),
  type: z.enum(['income', 'cancelled', 'expense', 'transfer', 'refund', 'investment', 'purchase', 'procurement']),
  direction: z.enum(['in', 'out']),
  account: z.object({
    id: idSchema,
    names: languageStringSchema,
  }),
  minorAmount: minorNumberSchema,
  minorBalanceBefore: z.number().nullable().optional(),
  minorBalanceAfter: z.number().nullable().optional(),
  currency: z.object({
    id: idSchema,
    names: languageStringSchema,
    symbols: languageStringSchema,
    scale: z.number(),
  }),
  cashregister: z.object({
    id: idSchema,
    names: languageStringSchema,
    priority: z.number(),
  }),
  description: z.string().optional(),
  sourceModel: z.enum(['manual', 'cashregister', 'cashregisterAccount', 'order', 'client', 'expense', 'procurement', 'supplier']),
  sourceId: idSchemaOptional,
  role: z.enum(['from', 'to']).nullable().optional(),
  transferId: idSchemaOptional,
  confirmed: z.boolean(),
  cancelled: z.boolean().optional(),
  awaitingReceive: z.boolean().optional(),
  confirmedBy: moneyTransactionActorSchema.optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  createdBy: moneyTransactionActorSchema.optional(),
  cancelledBy: moneyTransactionActorSchema.optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  removed: z.boolean().optional(),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
})

export const createMoneyTransactionRepoSchema = z.object({
  type: z.enum(['income', 'cancelled', 'expense', 'transfer', 'refund', 'investment', 'purchase', 'procurement']),
  currencyId: idSchema,
  minorAmount: minorNumberSchema,
  direction: z.enum(['in', 'out']),
  accountId: idSchema,
  cashregisterId: idSchema,
  sourceModel: z.enum(['manual', 'cashregister', 'cashregisterAccount', 'order', 'client', 'expense', 'procurement', 'supplier']),
  sourceId: idSchemaOptional,
  role: z.enum(['from', 'to']).nullable().optional(),
  transferId: idSchemaOptional,
  confirmed: z.boolean().optional(),
  confirmedBy: z.string().nullable().optional(),
  confirmedAt: z.coerce.date().nullable().optional(),
  createdBy: z.string().nullable().optional(),
  cancelled: z.boolean().optional(),
  cancelledBy: z.string().nullable().optional(),
  cancelledAt: z.coerce.date().nullable().optional(),
  minorBalanceBefore: z.number().nullable().optional(),
  minorBalanceAfter: z.number().nullable().optional(),
  description: z.string().optional(),
})
