services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: raw-frontend
    restart: always
    expose:
      - "80"
    networks:
      - shared_network
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raw-frontend.rule=Host(`raw.stoneremnant.pp.ua`)"
      - "traefik.http.routers.raw-frontend.entrypoints=websecure"
      - "traefik.http.routers.raw-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.raw-frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: raw-backend
    restart: always
    expose:
      - "3001"
    networks:
      - shared_network
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raw-backend.rule=Host(`apiraw.stoneremnant.pp.ua`)"
      - "traefik.http.routers.raw-backend.entrypoints=websecure"
      - "traefik.http.routers.raw-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.raw-backend.loadbalancer.server.port=3001"

networks:
  shared_network:
    external: true