services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: raw-rmnt-frontend
    restart: always
    expose:
      - "80"
    networks:
      - shared_network
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raw-rmnt-frontend.rule=Host(`raw.rmnt.me`)"
      - "traefik.http.routers.raw-rmnt-frontend.entrypoints=websecure"
      - "traefik.http.routers.raw-rmnt-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.raw-rmnt-frontend.loadbalancer.server.port=80"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: raw-rmnt-backend
    restart: always
    expose:
      - "3001"
    networks:
      - shared_network
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/storage:/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raw-rmnt-backend.rule=Host(`apiraw.rmnt.me`)"
      - "traefik.http.routers.raw-rmnt-backend.entrypoints=websecure"
      - "traefik.http.routers.raw-rmnt-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.raw-rmnt-backend.loadbalancer.server.port=3001"

networks:
  shared_network:
    external: true