services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dev-frontend
    restart: always
    ports:
      - "3060:80"
    networks:
      - shared_network
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dev-backend
    restart: always
    ports:
      - "3061:3001"
    networks:
      - shared_network
    env_file:
      - ./backend/.env
    volumes:
    - ./backend/storage:/app/storage
networks:
  shared_network:
    external: true
