import { enUS, ru, uk } from 'date-fns/locale'

export const DATE_LOCALE_MAP = {
  en: enUS,
  ru,
  uk,
}

export const backendUrl = import.meta.env.VITE_BACKEND_URL

export const SUPPORTED_LANGUAGES = ['ru', 'en'] as const
export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number]

export const NAV_MENU_ITEMS = [
  {
    id: 'dashboard',
    url: '/dashboard',
    icon: 'LayoutDashboard',
    permissions: ['dashboard.page'],
  },
  {
    id: 'orders',
    url: '/orders',
    icon: 'ShoppingCart',
    permissions: ['order.page'],
  },
  {
    id: 'leades',
    url: '/leades',
    icon: 'Users',
    permissions: ['lead.page'],
  },
  {
    id: 'chats',
    url: '/chats',
    icon: 'MessageSquare',
    permissions: ['chat.page'],
  },
  {
    id: 'tasks',
    url: '/tasks',
    icon: 'ListChecks',
    permissions: ['task.page'],
  },
  {
    id: 'catalog',
    icon: 'Package',
    permissions: ['product.page', 'attribute.page', 'attributeGroup.page', 'barcode.page', 'category.page'],
    items: [
      { id: 'products', url: '/products', permissions: ['product.page'] },
      { id: 'categories', url: '/categories', permissions: ['category.page'] },
      { id: 'productPropertiesGroups', url: '/product-properties-groups', permissions: ['product-properties-groups.page'] },
      { id: 'productProperties', url: '/product-properties', permissions: ['product-property.page'] },
      { id: 'barcodes', url: '/barcodes', permissions: ['barcode.page'] },
    ],
  },
  {
    id: 'statistic',
    icon: 'BarChart3',
    permissions: ['statistic.page', 'orderStatistic.page', 'productStatistic.page', 'stockStatistic.page'],
    items: [
      { id: 'orderStatistic', url: '/statistics/orders', permissions: ['orderStatistic.page'] },
      { id: 'productStatistic', url: '/statistic/product', permissions: ['productStatistic.page'] },
      { id: 'stockStatistic', url: '/statistic/stock', permissions: ['stockStatistic.page'] },
      { id: 'productionStatistic', url: '/statistic/production', permissions: ['productionStatistic.page'] },
      { id: 'metrics', url: '/statistic/metrics', permissions: ['metrics.page'] },
    ],
  },
  {
    id: 'marketing',
    icon: 'Tag',
    permissions: ['marketing.page', 'client.page', 'promocode.page', 'coupon.page', 'bonus.page'],
    items: [
      { id: 'clients', url: '/clients', permissions: ['client.page'] },
      { id: 'promocodes', url: '/promocodes', permissions: ['promocode.page'] },
      { id: 'coupons', url: '/coupons', permissions: ['coupon.page'] },
      { id: 'bonuses', url: '/bonuses', permissions: ['bonus.page'] },
    ],
  },
  {
    id: 'warehouses',
    icon: 'Warehouse',
    permissions: ['warehouse.page', 'purchase.page', 'procurement.page', 'production.page', 'inventory.page'],
    items: [
      { id: 'warehouses', url: '/warehouses', permissions: ['warehouses.page'] },
      { id: 'purchases', url: '/purchases', permissions: ['purchase.page'] },
      { id: 'procurements', url: '/procurements', permissions: ['procurement.page'] },
      { id: 'production', url: '/production', permissions: ['production.page'] },
      { id: 'inventories', url: '/inventories', permissions: ['inventory.page'] },
      { id: 'warehouseTransactions', url: '/warehouse-transactions', permissions: ['warehouse-transaction.page'] },
    ],
  },
  {
    id: 'money',
    icon: 'Banknote',
    permissions: ['money.page', 'cashregister.page', 'cashregister-account.page', 'expense.page', 'investor.page', 'supplier.page', 'money-transaction.page'],
    items: [
      { id: 'cashregisters', url: '/cashregisters', permissions: ['cashregister.page'] },
      {
        id: 'cashregisterAccounts',
        url: '/cashregister-accounts',
        permissions: ['cashregister-account.page'],
      },
      { id: 'expenses', url: '/expenses', permissions: ['expense.page'] },
      { id: 'investors', url: '/investors', permissions: ['investor.page'] },
      { id: 'suppliers', url: '/suppliers', permissions: ['supplier.page'] },
      { id: 'moneyTransactions', url: '/money-transactions', permissions: ['money-transaction.page'] },
      { id: 'balances', url: '/balances', permissions: ['balance.page'] },
    ],
  },
  {
    id: 'socials',
    icon: 'Globe',
    permissions: ['social.page', 'news.page', 'update.page', 'tour.page'],
    items: [
      { id: 'news', url: '/socials/news', permissions: ['news.page'] },
      { id: 'updates', url: '/updates', permissions: ['update.page'] },
      { id: 'tour', url: '/tour', permissions: ['tour.page'] },
    ],
  },
  {
    id: 'users',
    icon: 'Users',
    permissions: ['user.page', 'timetable.page', 'userRole.page'],
    items: [
      { id: 'users', url: '/users', permissions: ['user.page'] },
      { id: 'timetable', url: '/users/timetable', permissions: ['timetable.page'] },
      { id: 'userRoles', url: '/users/roles', permissions: ['userRole.page'] },
    ],
  },
  {
    id: 'settings',
    icon: 'Settings',
    permissions: ['settings.page', 'language.page', 'currency.page', 'source.page', 'orderStatus.page', 'deliveryService.page', 'unit.page', 'log.page'],
    items: [
      { id: 'automations', url: '/settings/automations', permissions: ['automation.page'] },
      { id: 'currencies', url: '/settings/currencies', permissions: ['currency.page'] },
      {
        id: 'deliveryServices',
        url: '/settings/delivery-services',
        permissions: ['deliveryService.page'],
      },
      { id: 'auditLogs', url: '/settings/audit-logs', permissions: ['audit-log.page'] },
      { id: 'languages', url: '/settings/languages', permissions: ['language.page'] },
      { id: 'orderSources', url: '/settings/order-sources', permissions: ['orderSource.page'] },
      { id: 'orderStatuses', url: '/settings/order-statuses', permissions: ['orderStatus.page'] },
      { id: 'expenseCategories', url: '/settings/expense-categories', permissions: ['expense-category.page'] },
      { id: 'settings', url: '/settings', permissions: ['settings.page'] },
      { id: 'sites', url: '/settings/sites', permissions: ['site.page'] },
      { id: 'units', url: '/settings/units', permissions: ['unit.page'] },
    ],
  },
  {
    id: 'documents',
    url: '/documents',
    icon: 'FileText',
    permissions: ['document.page'],
  },
]

export const SOCIAL_TYPES = [
  {
    id: 'telegram',
  },
  {
    id: 'instagram',
  },
  {
    id: 'whatsapp',
  },
  {
    id: 'viber',
  },
]

export const PAYMENT_STATUSES = [
  {
    id: 'pending',
  },
  {
    id: 'processing',
  },
  {
    id: 'paid',
  },
  {
    id: 'failed',
  },
  {
    id: 'cancelled',
  },
  {
    id: 'refunded',
  },
]

export const AUTOMATION_TRIGGERS = [
  {
    group: 'order',
    items: [
      {
        id: 'order-created',
      },
      {
        id: 'order-updated',
      },
      {
        id: 'order-removed',
      },
      {
        id: 'order-status-updated',
      },
    ],
  },
]

export const AUTOMATION_CONDITIONS = [
  {
    group: 'order',
    items: [
      {
        id: 'orderStatus',
        type: 'contains',
      },
      {
        id: 'orderSource',
        type: 'contains',
      },
      {
        id: 'deliveryService',
        type: 'contains',
      },
    ],
  },
]

export const AUTOMATION_ACTIONS = [
  {
    group: 'order',
    items: [
      {
        id: 'order-status-update',
      },
      {
        id: 'order-source-update',
      },
      {
        id: 'order-delivery-service-update',
      },
      {
        id: 'pay-order',
      },
    ],
  },
]

export const USER_ROLE_PERMISSIONS = [
  {
    group: 'orders',
    permissions: ['order.page', 'order.read', 'order.remove', 'order.create', 'order.edit', 'order.export', 'order.profit', 'order.auditLogs'],
  },
  {
    group: 'products',
    dependencies: ['language.read', 'category.read', 'unit.read', 'currency.read'],
    permissions: ['product.page', 'product.read', 'product.remove', 'product.create', 'product.edit', 'product.batchEdit', 'product.import', 'product.export', 'product.purchasePrice', 'product.quantityLogs', 'product.auditLogs'],
  },
  {
    group: 'categories',
    dependencies: ['language.read'],
    permissions: ['category.page', 'category.read', 'category.remove', 'category.create', 'category.edit', 'category.batchEdit', 'category.import', 'category.export', 'category.auditLogs'],
  },
  {
    group: 'product-property-group',
    dependencies: ['language.read'],
    permissions: ['productPropertyGroup.page', 'productPropertyGroup.read', 'productPropertyGroup.remove', 'productPropertyGroup.create', 'productPropertyGroup.edit', 'productPropertyGroup.auditLogs'],
  },
  {
    group: 'product-property',
    dependencies: ['language.read', 'productPropertyGroup.read'],
    permissions: ['productProperty.page', 'productProperty.read', 'productProperty.remove', 'productProperty.create', 'productProperty.edit', 'productProperty.auditLogs'],
  },
  {
    group: 'barcode',
    dependencies: ['language.read'],
    permissions: ['barcode.page', 'barcode.read', 'barcode.remove', 'barcode.create', 'barcode.edit', 'barcode.auditLogs'],
  },
  {
    group: 'order-statistic',
    dependencies: ['language.read', 'order.read'],
    permissions: ['orderStatistic.page', 'orderStatistic.read', 'orderStatistic.export', 'orderStatistic.profit'],
  },
  {
    group: 'client',
    dependencies: ['language.read', 'client.read'],
    permissions: ['client.page', 'client.read', 'client.remove', 'client.create', 'client.edit', 'client.export', 'client.auditLogs'],
  },
  {
    group: 'supplier',
    dependencies: ['language.read'],
    permissions: ['supplier.page', 'supplier.read', 'supplier.remove', 'supplier.create', 'supplier.edit', 'supplier.export', 'supplier.auditLogs'],
  },
  {
    group: 'warehouse',
    dependencies: ['language.read'],
    permissions: ['warehouse.page', 'warehouse.read', 'warehouse.remove', 'warehouse.create', 'warehouse.edit', 'warehouse.auditLogs'],
  },
  {
    group: 'warehouseTransaction',
    dependencies: ['language.read', 'warehouse.read'],
    permissions: ['warehouseTransaction.page', 'warehouseTransaction.read', 'warehouseTransaction.remove', 'warehouseTransaction.create', 'warehouseTransaction.edit', 'warehouseTransaction.export', 'warehouseTransaction.auditLogs'],
  },
  {
    group: 'unit',
    dependencies: ['language.read'],
    permissions: ['unit.page', 'unit.read', 'unit.remove', 'unit.create', 'unit.edit', 'unit.auditLogs'],
  },
  {
    group: 'cashregister',
    dependencies: ['language.read'],
    permissions: ['cashregister.page', 'cashregister.read', 'cashregister.remove', 'cashregister.create', 'cashregister.edit', 'cashregister.auditLogs'],
  },
  {
    group: 'cashregisterAccount',
    dependencies: ['language.read', 'cashregister.read'],
    permissions: ['cashregisterAccount.page', 'cashregisterAccount.read', 'cashregisterAccount.remove', 'cashregisterAccount.create', 'cashregisterAccount.edit', 'cashregisterAccount.auditLogs'],
  },
  {
    group: 'expense',
    dependencies: ['language.read'],
    permissions: ['expense.page', 'expense.read', 'expense.remove', 'expense.create', 'expense.edit', 'expense.export', 'expense.auditLogs'],
  },
  {
    group: 'moneyTransaction',
    dependencies: ['language.read', 'cashregister.read'],
    permissions: ['moneyTransaction.page', 'moneyTransaction.read', 'moneyTransaction.remove', 'moneyTransaction.create', 'moneyTransaction.edit', 'moneyTransaction.export'],
  },
  {
    group: 'user',
    dependencies: ['language.read', 'user-role.read'],
    permissions: ['user.page', 'user.read', 'user.remove', 'user.create', 'user.edit', 'user.auditLogs'],
  },
  {
    group: 'userRole',
    dependencies: ['language.read'],
    permissions: ['userRole.page', 'userRole.read', 'userRole.remove', 'userRole.create', 'userRole.edit', 'userRole.auditLogs'],
  },
  {
    group: 'language',
    permissions: ['language.page', 'language.read', 'language.remove', 'language.create', 'language.edit', 'language.auditLogs'],
  },
  {
    group: 'currency',
    dependencies: ['language.read'],
    permissions: ['currency.page', 'currency.read', 'currency.remove', 'currency.create', 'currency.edit', 'currency.auditLogs'],
  },
  {
    group: 'orderStatus',
    dependencies: ['language.read'],
    permissions: ['orderStatus.page', 'orderStatus.read', 'orderStatus.remove', 'orderStatus.create', 'orderStatus.edit', 'orderStatus.auditLogs'],
  },
  {
    group: 'balance',
    dependencies: ['balance.read'],
    permissions: ['balance.page', 'balance.read', 'balance.remove', 'balance.create', 'balance.auditLogs'],
  },
  {
    group: 'orderSource',
    dependencies: ['language.read'],
    permissions: ['orderSource.page', 'orderSource.read', 'orderSource.remove', 'orderSource.create', 'orderSource.edit', 'orderSource.auditLogs'],
  },
  {
    group: 'automation',
    dependencies: ['language.read'],
    permissions: ['automation.page', 'automation.read', 'automation.remove', 'automation.create', 'automation.edit'],
  },
  {
    group: 'deliveryService',
    dependencies: ['language.read'],
    permissions: ['deliveryService.page', 'deliveryService.read', 'deliveryService.remove', 'deliveryService.create', 'deliveryService.edit', 'deliveryService.auditLogs'],
  },
  {
    group: 'expenseCategory',
    dependencies: ['language.read'],
    permissions: ['expenseCategory.page', 'expenseCategory.read', 'expenseCategory.remove', 'expenseCategory.create', 'expenseCategory.edit', 'expenseCategory.auditLogs'],
  },
  {
    group: 'site',
    dependencies: ['language.read'],
    permissions: ['site.page', 'site.read', 'site.remove', 'site.create', 'site.edit', 'site.auditLogs'],
  },
  {
    group: 'settings',
    permissions: ['settings.page', 'settings.read', 'settings.remove', 'settings.edit'],
  },
  {
    group: 'other',
    permissions: ['other.admin'],
  },
] as const

export const ISO_COUNTRY_CODES = [
  'AF',
  'AX',
  'AL',
  'DZ',
  'AS',
  'AD',
  'AO',
  'AI',
  'AQ',
  'AG',
  'AR',
  'AM',
  'AW',
  'AU',
  'AT',
  'AZ',
  'BS',
  'BH',
  'BD',
  'BB',
  'BY',
  'BE',
  'BZ',
  'BJ',
  'BM',
  'BT',
  'BO',
  'BQ',
  'BA',
  'BW',
  'BV',
  'BR',
  'IO',
  'BN',
  'BG',
  'BF',
  'BI',
  'CV',
  'KH',
  'CM',
  'CA',
  'KY',
  'CF',
  'TD',
  'CL',
  'CN',
  'CX',
  'CC',
  'CO',
  'KM',
  'CG',
  'CD',
  'CK',
  'CR',
  'CI',
  'HR',
  'CU',
  'CW',
  'CY',
  'CZ',
  'DK',
  'DJ',
  'DM',
  'DO',
  'EC',
  'EG',
  'SV',
  'GQ',
  'ER',
  'EE',
  'SZ',
  'ET',
  'FK',
  'FO',
  'FJ',
  'FI',
  'FR',
  'GF',
  'PF',
  'TF',
  'GA',
  'GM',
  'GE',
  'DE',
  'GH',
  'GI',
  'GR',
  'GL',
  'GD',
  'GP',
  'GU',
  'GT',
  'GG',
  'GN',
  'GW',
  'GY',
  'HT',
  'HM',
  'VA',
  'HN',
  'HK',
  'HU',
  'IS',
  'IN',
  'ID',
  'IR',
  'IQ',
  'IE',
  'IM',
  'IL',
  'IT',
  'JM',
  'JP',
  'JE',
  'JO',
  'KZ',
  'KE',
  'KI',
  'KP',
  'KR',
  'KW',
  'KG',
  'LA',
  'LV',
  'LB',
  'LS',
  'LR',
  'LY',
  'LI',
  'LT',
  'LU',
  'MO',
  'MG',
  'MW',
  'MY',
  'MV',
  'ML',
  'MT',
  'MH',
  'MQ',
  'MR',
  'MU',
  'YT',
  'MX',
  'FM',
  'MD',
  'MC',
  'MN',
  'ME',
  'MS',
  'MA',
  'MZ',
  'MM',
  'NA',
  'NR',
  'NP',
  'NL',
  'NC',
  'NZ',
  'NI',
  'NE',
  'NG',
  'NU',
  'NF',
  'MK',
  'MP',
  'NO',
  'OM',
  'PK',
  'PW',
  'PS',
  'PA',
  'PG',
  'PY',
  'PE',
  'PH',
  'PN',
  'PL',
  'PT',
  'PR',
  'QA',
  'RE',
  'RO',
  'RU',
  'RW',
  'BL',
  'SH',
  'KN',
  'LC',
  'MF',
  'PM',
  'VC',
  'WS',
  'SM',
  'ST',
  'SA',
  'SN',
  'RS',
  'SC',
  'SL',
  'SG',
  'SX',
  'SK',
  'SI',
  'SB',
  'SO',
  'ZA',
  'GS',
  'SS',
  'ES',
  'LK',
  'SD',
  'SR',
  'SJ',
  'SE',
  'CH',
  'SY',
  'TW',
  'TJ',
  'TZ',
  'TH',
  'TL',
  'TG',
  'TK',
  'TO',
  'TT',
  'TN',
  'TR',
  'TM',
  'TC',
  'TV',
  'UG',
  'UA',
  'AE',
  'GB',
  'US',
  'UM',
  'UY',
  'UZ',
  'VU',
  'VE',
  'VN',
  'VG',
  'VI',
  'WF',
  'EH',
  'YE',
  'ZM',
  'ZW',
] as const

export type CountryCode = (typeof ISO_COUNTRY_CODES)[number]
