openapi: 3.0.0
info:
  title: Remnant API
  description: API для Remnant приложения
  version: "1.0.0"
servers:
  - url: http://localhost:5000/api
paths:
  /auth/register:
    post:
      summary: Регистрация нового пользователя
      description: Создание нового пользователя с email и паролем
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: secret123
              required:
                - email
                - password
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          description: Некорректные входные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /auth/login:
    post:
      summary: Авторизация пользователя
      description: Вход в систему с использованием email и пароля
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: secret123
              required:
                - email
                - password
      responses:
        "200":
          description: Успешная авторизация, возвращается JWT-токен
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        "400":
          description: Неверные учетные данные или ошибка авторизации
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: 60f6c2f7a2b4d72f9c8a1b2c
        email:
          type: string
          format: email
          example: user@example.com
        createdAt:
          type: string
          format: date-time
          example: "2025-02-02T10:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-02-02T10:00:00Z"
    Error:
      type: object
      properties:
        error:
          type: string
          example: Некорректные входные данные
