#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged

# После успешного lint-staged запускаем тесты бэкенда
cd backend && npm run test
BACK_TEST_RESULT=$?
cd ..

if [ $BACK_TEST_RESULT -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi
